services:
  api:
    build:
      context: .
      target: ${STAGE}

    container_name: easy-url-api
    image: ${ECR_REGISTRY}/easy-url-api:qa-${IMAGE_TAG}
    ports:
      - ${APP_PORT}:${APP_PORT}
    # env_file:
    #   - ./.env
